// front-react/src/MovieNode.tsx
import React from 'react';
import { IMovie } from "./types.ts";

interface IMovieProps {
    movie: IMovie;
    targetDeep: number;
    currentDeep: number;
}

const MovieNode: React.FC<IMovieProps> = ({ movie, currentDeep, targetDeep }) => {
    return (
        <div style={ {
            display: 'flex',
            flexDirection: 'column',
            gap: 1,
            border: '1px solid white',
            width: '100%',
            borderRadius: 5,
            padding: 1
        } }>
            { currentDeep === targetDeep ?
                <>
                    <span>{ movie.name }</span>
                </>
                :
                <>
                    <MovieNode movie={movie} targetDeep={targetDeep} currentDeep={currentDeep + 1}></MovieNode>
                    <MovieNode movie={movie} targetDeep={targetDeep} currentDeep={currentDeep + 1}></MovieNode>
                </>
            }
        </div>
    );
};

export default MovieNode;

// front-svelte/src/lib/MovieNode.svelte
<script lang="ts">
    import { type IMovie } from "../main";

    export let movie: IMovie;
    export let targetDeep: number;
    export let currentDeep: number;
</script>

<div class="movie-node">
    {#if currentDeep === targetDeep}
        <span>{ movie.name }</span>
    {:else}
        <svelte:self movie={movie} targetDeep={targetDeep} currentDeep={currentDeep + 1} />
        <svelte:self movie={movie} targetDeep={targetDeep} currentDeep={currentDeep + 1} />
    {/if}
</div>

<style lang="scss">
    .movie-node {
      display: flex;
      flex-direction: column;
      gap: 1px;
      border: 1px solid white;
      width: 100%;
      border-radius: 5px;
      padding: 1px;
    }
</style>
