// front-react/src/Movie.tsx
import React from 'react';
import { IMovie } from "./types.ts";

interface IMovieProps {
    movie: IMovie
}

const Movie: React.FC<IMovieProps> = ({ movie }) => {
    return (
        <div style={ {
            display: 'flex',
            flexDirection: 'column',
            border: '1px solid white',
            borderRadius: 5,
            marginBottom: 5
        } }>
            <span>{ movie.name }</span>
            <span>{ movie.genre }</span>
            <span>{ movie.previewImage }</span>
            <span>{ movie.previewVideoLink }</span>
        </div>
    );
};

export default Movie;

// front-svelte/src/lib/Movie.svelte
<script lang="ts">
    import { type IMovie } from "../main";

    export let movie: IMovie;
</script>

<div class="movie">
    <span>{ movie.name }</span>
    <span>{ movie.genre }</span>
    <span>{ movie.previewImage }</span>
    <span>{ movie.previewVideoLink }</span>
</div>

<style lang="scss">
    .movie {
      display: flex;
      flex-direction: column;
      border: 1px solid white;
      border-radius: 5px;
      margin-bottom: 5px;
    }
</style>
