// front-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";

  interface IMovie {
    id: string;
    name: string;
    previewImage: string;
    previewVideoLink: string;
    genre: string;
  }

  const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3000';

  const n: number = 128;

  let movies: IMovie[] = [];

  onMount(async () => {
    await fetch(`${BACKEND_URL}/movies/${n}`)
            .then(response => response.json())
            .then(data => {
              movies = [...movies, ...data]
            })
  })


  let count = 1;
</script>

<main>
  <div class='page'>
    <button id="render-btn" on:click={() => count += 1}>Render</button>
    <h4>Count: {count}</h4>
    <ul>
      {#each movies as {id, name, genre, previewImage, previewVideoLink} (id)}
        <li class="list-item">
          <span>{ name }</span>
          <span>{ genre }</span>
          <span>{ previewImage }</span>
          <span>{ previewVideoLink }</span>
          <span class="hidden">{ count }</span>
        </li>
      {/each}
    </ul>
  </div>
</main>

<style>
  .hidden {
    display: none;
  }
</style>

// front-angular/src/app/app.component.ts
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { MovieComponent } from "./movie/movie.component";
import { NgForOf } from "@angular/common";

export interface IMovie {
  id: string;
  name: string;
  previewImage: string;
  previewVideoLink: string;
  genre: string;
}

const BACKEND_URL = 'http://backend.local.dev';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MovieComponent, NgForOf],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit  {
  title = 'front-angular';

  n = 128;
  public moviesList: IMovie[] = []

  constructor(private cdr: ChangeDetectorRef) {}

  public ngOnInit(): void {
    fetch(`${BACKEND_URL}/movies/${this.n}`)
      .then(response => response.json())
      .then(data => this.moviesList = data)
  }

  public render() {
    this.cdr.detectChanges();
  }
}

<div class='page'>
  <button id="render-btn">Render</button>
  <ul>
    <app-movie *ngFor="let movie of moviesList" [movie]="movie"/>
  </ul>
</div>

<router-outlet />
